# Site settings
title: Digital Rewind
email: jeff@digitalrewind.com
description: > # this means to ignore newlines until "baseurl:"
  Jeff's thoughts and code for Javascript, CSS, Coldfusion, Lucee, Railo, MariaDB, MySQL and Linux 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://digitalrewind.com" # the base hostname & protocol for your site
twitter_username: hippiex
github_username:  hippiex
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
